language: ruby

rvm:
 - 2.0
 - 2.1
 - 2.2
 - ruby-head
 - jruby
 - jruby-head

gemfile:
  - Gemfile
  - gemfiles/rails-4-0-stable.gemfile
  - gemfiles/rails-4-1-stable.gemfile
  - gemfiles/rails-4-2-stable.gemfile
  - gemfiles/rails-master.gemfile

sudo: false

before_script:
  - psql -c 'create database carrierwave_test;' -U postgres

matrix:
  exclude:
    - rvm: 2.0.0
      gemfile: gemfiles/rails-master.gemfile
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head

notifications:
  email: false

addons:
  postgresql: "9.3"
